version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - /mnt/data2/wikijs/db:/var/lib/postgresql/data
    networks:
      - internal

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    volumes:
      - /mnt/data2/wikijs/repo:/home/node/repo
    networks:
      - internal

  cloudflared:
    image: ghcr.io/milgradesec/cloudflared:latest
    user: root
    command: tunnel
    environment:
      - TUNNEL_HOSTNAME=wiki.yude.jp
      - TUNNEL_URL=http://wiki:3000
      - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    networks:
      - internal
    restart: always

networks:
  internal: