version: "3"

services:
  web:
    image: pandentia/pleroma:latest
    ports:
    - "4020:4000"
    volumes:
      - ./data/pleroma/config/prod.secret.exs:/pleroma/config/prod.secret.exs
      - ./data/pleroma/uploads:/pleroma/uploads/

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: pleroma
      POSTGRES_DB: pleroma
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
