version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - /home/yude/docker-compose/jellyfin/config:/config
      - /mnt/data1/encoded:/data/encoded
      - /mnt/data1/Music:/data/music
      - /home/yude/docker-compose/docker-mirakurun-epgstation/recorded:/data/recorded
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
