version: '2.3'

services:
  statping:
    container_name: statping
    image: statping/statping:dev
    restart: always
    volumes:
      - ./data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8081:8080