version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
      - PLEX_CLAIM=claim-SD4wSKjTgRa9A9BDcgfn
    network_mode: host
    volumes:
      - ./data/config:/config
      - ./data/transcode:/transcode
      - ./data/media:/data
      - /mnt/data1/encoded:/encoded
      - /mnt/data4/recorded:/recorded
