version: '3'
services:
  xteve:
    image: tnwhitwell/xteve:latest
    ports:
      - "34400:34400"
    volumes:
      - "./data/config:/config"
      - "/tmp/xteve:/tmp/xteve"
    user: "${PUID}:${PGID}"
    environment:
      - TZ=Asia/Tokyo
    restart: always
