version: '3.8'

services:
  server:
    container_name: annict-profile-card
    image: slashnephy/annict-profile-card
    restart: always
    ports:
      - 8222:8080/tcp
    environment:
      ANNICT_TOKEN: 
      RUST_LOG: info,annict_profile_card=debug
