version: '3'

services:
    cloudflared-misskey:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=misskey.yude.jp
            - TUNNEL_URL=http://192.168.0.80:81
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - './.config:/root/.cloudflared' # bind mount with cert.pem in it

    cloudflared-mastodon:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=mstdn.yude.jp
            - TUNNEL_URL=http://192.168.0.80:85
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - './.config:/root/.cloudflared' # bind mount with cert.pem in it

    cloudflared-pleroma:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=pleroma.yude.jp
            - TUNNEL_URL=http://192.168.0.80:86
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - './.config:/root/.cloudflared' # bind mount with cert.pem in it

    cloudflared-roundcube:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=roundcube.yude.jp
            - TUNNEL_URL=http://192.168.0.80:9002
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - './.config:/root/.cloudflared' # bind mount with cert.pem in it

    cloudflared-bluemap:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=bluemap.yude.jp
            - TUNNEL_URL=http://192.168.0.80:8100
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - './.config:/root/.cloudflared' # bind mount with cert.pem in it

    cloudflared-h5ai:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=files.yude.jp
            - TUNNEL_URL=http://192.168.0.80:8801
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - './.config:/root/.cloudflared' # bind mount with cert.pem in it

    cloudflared-galactus:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=galactus.yude.jp
            - TUNNEL_URL=http://192.168.0.80:4600
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - './.config:/root/.cloudflared' # bind mount with cert.pem in it
