version: '3'

services:
    cloudflared-misskey:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=misskey.yude.jp
            - TUNNEL_URL=http://host.docker.internal:81
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always

    cloudflared-mastodon:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=mstdn.yude.jp
            - TUNNEL_URL=http://host.docker.internal:85
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always

    cloudflared-pleroma:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=pleroma.yude.jp
            - TUNNEL_URL=http://host.docker.internal:86
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always

    cloudflared-roundcube:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=roundcube.yude.jp
            - TUNNEL_URL=http://host.docker.internal:9002
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always

    cloudflared-bluemap:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=bluemap.yude.jp
            - TUNNEL_URL=http://host.docker.internal:8100
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always

    cloudflared-h5ai:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=files.yude.jp
            - TUNNEL_URL=http://host.docker.internal:8801
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always

    cloudflared-galactus:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=galactus.yude.jp
            - TUNNEL_URL=http://host.docker.internal:4600
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always
    
    cloudflared-nextcloud:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=nc.yude.jp
            - TUNNEL_URL=http://host.docker.internal:9000
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always
            
    cloudflared-wikijs:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=wiki.yude.jp
            - TUNNEL_URL=http://host.docker.internal:9202
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always

    cloudflared-gitea:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=git.yude.jp
            - TUNNEL_URL=http://host.docker.internal:3020
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always
