version: '3'

services:
    cloudflared-misskey:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=misskey.yude.jp
            - TUNNEL_URL=http://192.168.0.80:81
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - './.config:/root/.cloudflared' # bind mount with cert.pem in it

    cloudflared-mastodon:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=mstdn.yude.jp
            - TUNNEL_URL=http://192.168.0.80:85
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - './.config:/root/.cloudflared' # bind mount with cert.pem in it