version: '3'

services:
    cloudflared-bluemap:
        image: cloudflare/cloudflared:2021.8.3
        user: root
        command: tunnel
        environment:
            - TUNNEL_HOSTNAME=bluemap.yude.jp
            - TUNNEL_URL=http://host.docker.internal:8100
            - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
        volumes:
            - '$HOME/.cloudflared:/root/.cloudflared'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always
