version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./data/html:/var/www/html
      - /mnt/data1:/storage/data1
      - /mnt/data2:/storage/data2
      - /mnt/data4:/storage/data4
      - /mnt/data5:/storage/data5
    environment:
      - VIRTUAL_HOST=nc.yude.jp
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./data/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 8089:80
    volumes:
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

networks:
  proxy-tier:
